# Assignment

### Jawaban No 1

In [8]:
import numpy as np

In [9]:
from numpy import random

In [10]:
random.randint(0,3, size=(4,4))

array([[2, 2, 0, 2],
       [1, 0, 2, 2],
       [2, 1, 2, 2],
       [2, 1, 1, 2]])

### Jawaban No 2

In [11]:
x = random.randint(0,16, size=(4,4))
x

array([[13,  7,  6,  2],
       [ 8, 13,  4,  7],
       [ 7,  7,  3,  1],
       [ 8,  4,  7,  9]])

In [12]:
y = np.hsplit(x, 2)
y

[array([[13,  7],
        [ 8, 13],
        [ 7,  7],
        [ 8,  4]]),
 array([[6, 2],
        [4, 7],
        [3, 1],
        [7, 9]])]