# Exercise 4

### Jawaban No 1

In [2]:
import numpy as np

In [3]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
a[4] = 11
a

array([ 0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.,  0.])

### Jawaban No 2

In [4]:
b = np.ones((2, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
b.shape

(2, 3)

In [6]:
c = b.reshape(3, 2)
c

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
c.shape

(3, 2)

### Jawaban No 3

In [8]:
d = np.ones((5, 5))
d

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
d[1,1:4] = 0
d[2,1:4] = 0
d[3,1:4] = 0
d

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### Jawaban No 4

In [11]:
z = np.array([[[0, 1, 3],
               [5, 7, 9],
               [6, 8, 10]],
              
              [[0, 2, 4],
               [6, 8, 10],
               [0, 1, 3]],
             
              [[1, 1, 2],
               [5, 2, 9],
               [1, 3, 3]]])
z

array([[[ 0,  1,  3],
        [ 5,  7,  9],
        [ 6,  8, 10]],

       [[ 0,  2,  4],
        [ 6,  8, 10],
        [ 0,  1,  3]],

       [[ 1,  1,  2],
        [ 5,  2,  9],
        [ 1,  3,  3]]])

In [12]:
z[2, 1, 1]

2